# -- Environment Variables --
# Set editor
export EDITOR='nvim'

# Add scripts folder to PATH
export PATH="$HOME/.config/scripts:$PATH"


# Set man pager
# export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"

# -- History Configuration --
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=50000
export SAVEHIST=10000

# append history to share between tmux sessions
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_SPACE

# -- Aliases --
# vim
alias vim=nvim
alias view="nvim -R"

alias avim='NVIM_APPNAME=astrovim nvim'

alias ta='tmux attach -t $(tmux list-sessions -F "#{session_name}" | fzf)'
alias tn='tmux new -s'

alias lg="lazygit"

alias mssh='~/.config/scripts/morphcloud-ssh-fzf.sh'

# Miller
alias mcsv='mlr --csv --from'
alias mcsvp='mlr --csv --opprint --from'

# Git
alias gs="git branch --sort=-committerdate | fzf --preview 'git show --color=always {-1}' --tmux --height 40% --layout reverse \
--bind 'enter:become(git switch {-1})'"

# ax-agent
alias ax='ax-agent'




# -- vi mode --
bindkey -v
# 10ms for key sequences
KEYTIMEOUT=1
# fix bindkey escape strangeness
bindkey "^?" backward-delete-char

# Ctrl-P and Ctrl-N to scroll through recent history in insert mode
bindkey -M viins '^P' up-history
bindkey -M viins '^N' down-history

# Vi mode cursor shape indicator
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
    # Normal mode - block cursor
    echo -ne '\e[1 q'
  else
    # Insert mode - beam cursor
    echo -ne '\e[5 q'
  fi
}

function zle-line-init {
  # Start in insert mode with beam cursor
  echo -ne '\e[5 q'
}

# Reset cursor to beam when command is executed
function zle-line-finish {
  echo -ne '\e[5 q'
}

zle -N zle-keymap-select
zle -N zle-line-init
zle -N zle-line-finish


# Configure editing commands in vim
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

# Widget to run current command in new tmux pane
tmux_split_with_current_command() {
  # First check if we're in a tmux session
  if [[ -z "$TMUX" ]]; then
    zle -M "Not in a tmux session"
    return 1
  fi

  # Get the current command line content
  local cmd="$BUFFER"
  
  # Only proceed if there's actually a command
  if [[ -n "$cmd" ]]; then
    # Execute tmux split-window with the current command
    # Using zsh's silent command execution with the () syntax
    (tmux split-window -h "$cmd" &)
    
    # Clear the editing buffer
    BUFFER=""; CURSOR=0; zle redisplay
  fi
}

# Create the widget from the function
zle -N tmux_split_with_current_command

# Bind Ctrl-\ to the widget
bindkey '^\' tmux_split_with_current_command


# OSC 133 prompt jump so tmux can jump to last prompt
preexec () {
  echo -n "\\x1b]133;A\\x1b\\"
}

# -- plugins --
# Pure prompt
fpath+=(~/.config/zsh/pure)
autoload -U promptinit; promptinit
prompt pure

# fzf-tab
autoload -U compinit; compinit
source ~/.config/zsh/fzf-tab/fzf-tab.plugin.zsh

# TODO fish like highlighting and autosuggestions
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# -- setup programs with shell interaction --

# -- FZF --
# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

# Jump to a git repository managed by ghq
gr() {
    local dir
    dir=$(ghq list | fzf --height 40% --reverse) && cd "$(ghq root)/$dir"
}

# mac ALT-C hack for fzf cd
bindkey "ç" fzf-cd-widget

# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

## Source secrets
source ~/.config/zsh/secrets

# fzf-git commands
# source ~/.config/zsh/fzf-git.sh

# -- Zoxide --
# eval "$(zoxide init zsh)"

# -- br --
# source /Users/austinletson/.config/broot/launcher/bash/br


. "$HOME/.local/bin/env"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/austinletson/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/austinletson/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/austinletson/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/austinletson/google-cloud-sdk/completion.zsh.inc'; fi
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

# SSL certificates for Python
export SSL_CERT_FILE=$(python3 -m certifi)
export REQUESTS_CA_BUNDLE=$(python3 -m certifi)
